### ISSUE TITLE
system libyaml

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vubiostat/r-yaml#102]
Can you provide a method to link to systemwide libyaml instead of the bundled one?

**Comment by spgarbet** [comment]
Why would such a behavior be desirable? Is this a way to get 1.2 support?

**Comment by Alessandro-Barbieri** [comment]
As now 1.2 isn't ready in libyaml https://github.com/yaml/libyaml/issues/20

You can get an idea of why bundling is bad here https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries

**Comment by spgarbet** [comment]
The current issue with this is that the current version of libyaml has a patch for indentation that doesn't not exist upstream. Indentation will break unless libyaml accepts that patch upstream if this is implemented.

**Comment by Alessandro-Barbieri** [comment]
Have you proposed that patch upstream?

**Comment by spgarbet** [comment]
I inherited this project. The patch was not proposed upstream. I'm doing diffs now to determine the scope of the patch. The secondary investigation is what compile flags exist and do for the libyaml library.

**Comment by spgarbet** [comment]
I think this is difference.
[indent_mapping_sequence.txt](https://github.com/vubiostat/r-yaml/files/8035787/indent_mapping_sequence.txt)
e

**Comment by spgarbet** [comment]
I submitted the modifications as a pull request to the libyaml project. They had some outstanding tickets the pull request would solve. There's hope these two can be brought to the same version.

**Comment by spgarbet** [comment]
Pull requests were rejected. I cannot use the system library and get the expected behavior. I tried changed these things to the default of the library and the `data.table` project immediately complained. There's no way to fix this unfortunately without the upstream library maintainers cooperation, short of changing libraries. 

I started this project to change over to a yaml12 supported library: https://github.com/vubiostat/yaml12

I'll make it so it uses the system library.
