### ISSUE TITLE
Should `column.major = TRUE` be the default for `as.yaml` and `write.yaml` from df?

### ISSUE THREAD

**Issue by julianbarg** [vubiostat/r-yaml#142]
While the output is technically a valid yaml file, the default `column.major = T` yaml output is not idiomatic. Textbook examples of valid yaml data are organized by observation. I could foresee this breaking some dependencies, but if there is some support for this -- anyone out there, what do you think? -- maybe we should change the default?

**Comment by spgarbet** [comment]
This package has major downstream dependencies. Any changes require sign off by the RStudio core team and data.table. I made a slight change in spacing in one patch and it ended up getting reverted due to downstream dependencies. Changing the default would require a lot of buy-in. @hadley would this be something you would welcome?

**Comment by hadley** [comment]
Regardless of the technical merits of the change, I think it's too big at this point in yaml's lifecycle — it would cause a huge amount of downstream pain.
