### ISSUE TITLE
Why does \n become |2+?

### ISSUE THREAD

**Issue by MichaelChirico** [vubiostat/r-yaml#75]
```
as.yaml(list(a = '\n'))
# [1] "a: |2+\n\n"
as.yaml(list(a = '\r\n'))
# [1] "a: \"\\r\\n\"\n"
```

The behavior seems inconsistent, and the first case is a bit strange. I would expect the output in the first case to be `"a: \"\\n\"\n"`, or the second case to also be garbled.

**Comment by viking** [comment]
This is a quirk of libyaml formatting. In your first example, if you roundtrip the list, you get the same result back:

```r
a <- list(a = '\n')
b <- yaml.load(as.yaml(x))
all.equal(a, b) #=> TRUE
```

In the second example, you don't get exactly the same result after roundtrip because libyaml collapses `\r\n` into just `\n`.

```r
a <- list(a = '\r\n')
b <- yaml.load(as.yaml(x))
print(a)
# $a
# [1] "\r\n"
print(b)
# $a
# [1] "\n"
```

Check out more information [in the YAML 1.1 spec](https://yaml.org/spec/1.1/current.html#c-b-block-header(s,m,t)) regarding the weird looking `|2+` block indicator.

**Comment by spgarbet** [comment]
Works as specified by YAML 1.1
