### ISSUE TITLE
verbatim class is not always handled

### ISSUE THREAD

**Issue by dmurdoch** [vubiostat/r-yaml#97]
In this SO question, https://stackoverflow.com/q/66207086/2554330, the user had an example which included elements like this:

    tab <- list(block = "[]", link = "~")

He wanted to convert it to YAML, with the output looking like this:

    block: []
    link: ~

but of course `as.yaml(tab)` adds quotes:

    library(yaml) # Jan 30 devel version 4788abe3
    cat(as.yaml(tab))
    # block: '[]'
    # link: '~'

In the docs it says, "Character vectors that have a class of ‘verbatim’ will not be quoted in the output YAML document except when the YAML specification requires it.", so I figured a handler that converted characters to class verbatim would do what he wanted.  Indeed, it works for the `link` entry, but not the `block` entry:

    cat(as.yaml(tab, handlers = list(character = function(x) structure(x, class="verbatim"))))
    # block: '[]'
    # link: ~

But clearly the user's desired output is legal YAML, so this looks like a bug in `as.yaml`.

**Comment by viking** [comment]
When using the verbatim class, the yaml package will try to convert it to a YAML scalar string. Unquoted `[]` is a YAML sequence object, and so the underlying libyaml library quotes the string in order to make sure it stays as a string. Instead of:

`tab <- list(block = "[]", link = "~")`

This would work instead:

`tab <- list(block = list(), link = "~")`
